theme: minima
title: Meandering Philosophy
author: Balan Selvamuthukumaran
description: Thoughts on philosophy, literature, the outdoors, and the connection of all things (while taking care to maintain no semblance of structure, meandering in all ways.)
